{application,sprinter,
             [{description,"Service discovery with Mesos and Kubernetes."},
              {vsn,"0.1.0"},
              {registered,[]},
              {mod,{sprinter_app,[]}},
              {applications,[kernel,stdlib]},
              {env,[]},
              {modules,[sprinter,sprinter_app,sprinter_backend,
                        sprinter_compose,sprinter_config,sprinter_kubernetes,
                        sprinter_mesos,sprinter_mochiglobal,sprinter_sup]},
              {maintainers,[]},
              {licenses,[]},
              {links,[]}]}.
